export enum PetActionTypes {
  FETCH_PETS_REQUEST = "FETCH_PETS_REQUEST",
  FETCH_PETS_SUCCESS = "FETCH_PETS_SUCCESS",
  FETCH_PETS_FAILURE = "FETCH_PETS_FAILURE",

  CREATE_PET_REQUEST = "CREATE_PET_REQUEST",
  CREATE_PET_SUCCESS = "CREATE_PET_SUCCESS",
  CREATE_PET_FAILURE = "CREATE_PET_FAILURE",

  ADD_TO_FAVORITES = "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES",

  SEARCH_PETS = "SEARCH_PETS",
  FILTER_PETS = "FILTER_PETS",
}

export enum CartActionTypes {
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  CLEAR_CART = "CLEAR_CART",
}

export enum AuthActionTypes {
    REGISTER_REQUEST = "REGISTER_REQUEST",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
    REGISTER_FAILURE = "REGISTER_FAILURE",
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    LOGOUT = "LOGOUT",
    LOAD_USER_FAILURE = "LOAD_USER_FAILURE",
    LOAD_USER_REQUEST = "LOAD_USER_REQUEST",
    LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
}